version: "3"

services:
  crypto-trading:
    build: .
    container_name: binance_trader
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./supported_coin_list:/app/supported_coin_list
      - ./data:/app/data
      - ./logs:/app/logs
      - ./:/app
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1


  api:
    build: .
    container_name: binance_trader_api
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./data:/app/data
      - ./logs:/app/logs
      - ./:/app
    ports:
      - 5123:5123
    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
    depends_on:
      - crypto-trading
  # db:
  #   image: mongo:latest
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=superman
  #     - MONGO_INITDB_ROOT_PASSWORD=YTg9p6Cc2VyY7WEA894yJ2bcj8
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   ports:
  #     - "27018:27017"

  # sqlitebrowser:
  #   image: ghcr.io/linuxserver/sqlitebrowser
  #   container_name: sqlitebrowser
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Berlin
  #   volumes:
  #     - ./data/config:/config
  #     - ./data:/data
  #   ports:
  #     - 3000:3000
